### ISSUE TITLE
git-checkout: no commit found matching id: a929815925c174fe1ba0c3e9564954e4a913ad63

### ISSUE THREAD

**Issue by inwalkeddub** [mbutterick/br-parser-tools#3]
Hi, I'm new to racket and tools and your book. Got this during setup:

/Volumes/dev/racket$ raco pkg install --auto beautiful-racket
Resolving "beautiful-racket" via https://download.racket-lang.org/releases/6.12/catalog/
Resolving "beautiful-racket" via https://pkgs.racket-lang.org
Downloading repository git://github.com/mbutterick/beautiful-racket/?path=beautiful-racket
00: Resolving "sugar" via https://download.racket-lang.org/releases/6.12/catalog/
01: Resolving "beautiful-racket-lib" via https://download.racket-lang.org/releases/6.12/catalog/
02: Resolving "beautiful-racket-demo" via https://download.racket-lang.org/releases/6.12/catalog/
03: Resolving "brag" via https://download.racket-lang.org/releases/6.12/catalog/
03: Resolving "brag" via https://pkgs.racket-lang.org
00: Resolving "sugar" via https://pkgs.racket-lang.org
02: Resolving "beautiful-racket-demo" via https://pkgs.racket-lang.org
01: Resolving "beautiful-racket-lib" via https://pkgs.racket-lang.org
Resolving "br-parser-tools-lib" via https://download.racket-lang.org/releases/6.12/catalog/
Resolving "br-parser-tools-lib" via https://pkgs.racket-lang.org
Downloading repository git://github.com/mbutterick/sugar
Using cached15298614211529861421641 for git://github.com/mbutterick/beautiful-racket/?path=beautiful-racket-lib
Using cached15298614211529861421641 for git://github.com/mbutterick/beautiful-racket/?path=beautiful-racket-demo
Downloading repository https://github.com/mbutterick/brag.git
Downloading repository https://github.com/mbutterick/br-parser-tools.git?path=br-parser-tools-lib
git-checkout: no commit found matching id: a929815925c174fe1ba0c3e9564954e4a913ad63
  context...:
   /Applications/Racket v6.12/collects/net/git-checkout.rkt:604:0: find-commit-as-reference
   /Applications/Racket v6.12/collects/net/git-checkout.rkt:157:11
   /Applications/Racket v6.12/collects/net/git-checkout.rkt:54:2: retry-loop
   /Applications/Racket v6.12/collects/pkg/private/download.rkt:102:2: download!
   /Applications/Racket v6.12/collects/file/cache.rkt:63:2: fetch-and-continue
   /Applications/Racket v6.12/collects/racket/contract/private/arrow-val-first.rkt:428:3
   /Applications/Racket v6.12/collects/pkg/private/download.rkt:94:0: download-repo!24
   /Applications/Racket v6.12/collects/pkg/private/stage.rkt:300:11
   /Applications/Racket v6.12/collects/pkg/private/stage.rkt:107:0: stage-package/info46
   [repeats 1 more time]
   /Applications/Racket v6.12/collects/pkg/private/install.rkt:659:4: for-loop
   /Applications/Racket v6.12/collects/pkg/private/install.rkt:141:0: install-packages76
   /Applications/Racket v6.12/collects/pkg/private/../../racket/private/more-scheme.rkt:261:28
   /Applications/Racket v6.12/collects/racket/contract/private/arrow-val-first.rkt:428:3
   /Applications/Racket v6.12/collects/racket/file.rkt:378:8
   /Applications/Racket v6.12/collects/racket/file.rkt:334:2: loop
   ...
/Volumes/dev/racket$ racket -l br/test
standard-module-name-resolver: collection not found
  for module path: (lib "br/test")
  collection: "br"
  in collection directories:
   /Users/kevinrathbun/Library/Racket/6.12/collects
   /Applications/Racket v6.12/collects
   ... [163 additional linked and package directories]
  context...:
   show-collection-err
   standard-module-name-resolver

I guess its related to this package info on https://pkgs.racket-lang.org/package/br-parser-tools-lib ?

<img width="1155" alt="screen shot 2018-06-24 at 10 49 45 am" src="https://user-images.githubusercontent.com/18218688/41821921-a0f962dc-779c-11e8-8580-bc5827a07a83.png">

**Comment by mbutterick** [comment]
Sorry, that was my fault. I believe the package server is updated now and `raco pkg install --auto beautiful-racket` will work correctly.

**Comment by inwalkeddub** [comment]
Thanks! I think same fix needed here too:

...
Downloading repository https://github.com/mbutterick/br-parser-tools.git?path=br-parser-tools-doc
git-checkout: no commit found matching id: a929815925c174fe1ba0c3e9564954e4a913ad63

**Comment by mbutterick** [comment]
OK, I believe that one is fixed too. Sorry again.

**Comment by inwalkeddub** [comment]
No need to apologize, I'm excited to read your book!

/Volumes/dev/racket$ racket -l br/test
You installed beautiful-racket v1.1 correctly.
