### ISSUE TITLE
Tokens can't be imported

### ISSUE THREAD

**Issue by glmdgrielson** [mbutterick/br-parser-tools#4]
I've found a bit of an issue in that the `define-tokens` syntax creates a reference to `make-terminal-def`
which for some reason doesn't get imported when I require the tokens. It's a confusing and unexpected error for a seemingly innocous action. What gives?

**Comment by mbutterick** [comment]
A code sample would be helpful. I haven’t run across this before.

**Comment by glmdgrielson** [comment]
Got it.
```racket
;;; tokens.rkt
(require br-parser-tools/lex)
(provide (all-defined-out))
(define-tokens attributes/t
  (shebang shebang-line
           inner-doc-comment
           outer-doc-comment))
```
and
```racket
;;; lex.rkt
(require "tokens.rkt")
```

I **used** to get an error saying `make-terminal-def` was not bound. It's stopped now. I'll close this then.
